name: Deploy to Staging (Manual)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deploy to staging environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
      branch:
        description: 'Branch to deploy (default: 1.x)'
        required: false
        default: '1.x'

jobs:
  deploy-staging:
    name: Manual Staging Deployment
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress --optimize-autoloader --no-dev


      - name: Deploy to staging
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USERNAME }}
          key: ${{ secrets.STAGING_SSH_KEY }}
          port: ${{ secrets.STAGING_PORT }}
          script: |
            cd ${{ secrets.STAGING_PATH }}
            git pull origin ${{ github.event.inputs.branch }}
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force
            php artisan cache:clear
            php artisan config:cache
            sudo service nginx restart

      - name: Notify staging deployment
        uses: slackapi/slack-github-action@v2.1.1
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: "Staging deployment from branch ${{ github.event.inputs.branch }} ${{ job.status }}"
            blocks:
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "Staging deployment from branch ${{ github.event.inputs.branch }} ${{ job.status }}"
